---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-otc-peertech-de-v1alpha1-natgateway
  failurePolicy: Fail
  name: vnatgateway-v1alpha1.kb.io
  rules:
  - apiGroups:
    - otc.peertech.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - natgateways
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-otc-peertech-de-v1alpha1-network
  failurePolicy: Fail
  name: vnetwork-v1alpha1.kb.io
  rules:
  - apiGroups:
    - otc.peertech.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-otc-peertech-de-v1alpha1-providerconfig
  failurePolicy: Fail
  name: vproviderconfig-v1alpha1.kb.io
  rules:
  - apiGroups:
    - otc.peertech.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - providerconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-otc-peertech-de-v1alpha1-publicip
  failurePolicy: Fail
  name: vpublicip-v1alpha1.kb.io
  rules:
  - apiGroups:
    - otc.peertech.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - publicips
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-otc-peertech-de-v1alpha1-securitygroup
  failurePolicy: Fail
  name: vsecuritygroup-v1alpha1.kb.io
  rules:
  - apiGroups:
    - otc.peertech.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - securitygroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-otc-peertech-de-v1alpha1-securitygrouprule
  failurePolicy: Fail
  name: vsecuritygrouprule-v1alpha1.kb.io
  rules:
  - apiGroups:
    - otc.peertech.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - securitygrouprules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-otc-peertech-de-v1alpha1-snatrule
  failurePolicy: Fail
  name: vsnatrule-v1alpha1.kb.io
  rules:
  - apiGroups:
    - otc.peertech.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - snatrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-otc-peertech-de-v1alpha1-subnet
  failurePolicy: Fail
  name: vsubnet-v1alpha1.kb.io
  rules:
  - apiGroups:
    - otc.peertech.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - subnets
  sideEffects: None
