# This rule is not used by the project otc-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the otc.peertech.de.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: otc-operator
    app.kubernetes.io/managed-by: kustomize
  name: providerconfig-editor-role
rules:
- apiGroups:
  - otc.peertech.de
  resources:
  - providerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - otc.peertech.de
  resources:
  - providerconfigs/status
  verbs:
  - get
