# This rule is not used by the project otc-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over otc.peertech.de.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: otc-operator
    app.kubernetes.io/managed-by: kustomize
  name: publicip-admin-role
rules:
- apiGroups:
  - otc.peertech.de
  resources:
  - publicips
  verbs:
  - '*'
- apiGroups:
  - otc.peertech.de
  resources:
  - publicips/status
  verbs:
  - get
